const DEFAULT_API="https://restaurant-demand-ai.onrender.com";
const state={api:localStorage.getItem("rdai_api_url")||DEFAULT_API,data:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d}):"—";
const rc=v=>String(v||"LOW").toLowerCase();
function toast(x){$("toast").textContent=x;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),2500)}
function connection(ok,text){$("statusDot").className=ok?"ok":"bad";$("statusText").textContent=text}
async function api(payload){connection(false,"Connecting...");const r=await fetch(state.api.replace(/\/$/,"")+"/api/v1/client/intelligence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw Error("API HTTP "+r.status);const d=await r.json();if(!d.actions)throw Error("Invalid API response");connection(true,"Connected");return d}
function actions(){return [...(state.data?.actions||[])].sort((a,b)=>({HIGH:0,MODERATE:1,LOW:2}[a.priority]??9)-({HIGH:0,MODERATE:1,LOW:2}[b.priority]??9))}
function outletName(a){return a.outlet?.outlet_name||a.outlet?.outlet_id||"Unknown outlet"}
function productName(a){return a.product?.product_name||a.product?.product_id||"Unknown product"}
function render(){
 if(!state.data){$("empty").classList.remove("hidden");$("content").classList.add("hidden");return}
 $("empty").classList.add("hidden");$("content").classList.remove("hidden");
 const s=state.data.summary||{};$("mOutlets").textContent=n(s.outlets_analyzed);$("mProducts").textContent=n(s.products_analyzed);$("mHigh").textContent=n(s.high_priority);$("mOrders").textContent=n(s.replenishment_actions);$("date").textContent=state.data.report_date?"Report: "+state.data.report_date:"Report";
 const top=actions().slice(0,6);$("priority").innerHTML=top.map(a=>card(a)).join("");
 const om=outletMap();$("snapshot").innerHTML=om.sort((a,b)=>b.high-a.high).slice(0,6).map(outletCard).join("");
 renderRequirements();renderOutlets();renderProducts()
}
function card(a){return `<article class="card ${rc(a.priority)}"><div class="card-top"><div><b>${esc(outletName(a))}</b><div class="sub">${esc(productName(a))}</div></div><span class="badge ${rc(a.priority)}">${esc(a.priority||"LOW")}</span></div><div class="big">${n(a.forecast?.d1,2)} <small>${esc(a.forecast?.unit||"")} tomorrow</small></div><div class="row"><span>Current stock</span><b>${n(a.inventory?.current_inventory,2)}</b></div><div class="row"><span>Recommended order</span><b>${n(a.supply?.recommended_order,2)}</b></div><div class="row"><span>Stockout risk</span><b>${esc(a.stockout_risk||"LOW")}</b></div><div class="action ${String(a.recommendation?.action||"").toLowerCase()}">${esc(a.recommendation?.action||"MONITOR")} · ${esc(a.recommendation?.reason||"")}</div></article>`}
function outletMap(){const m=new Map();for(const a of state.data.actions||[]){const id=a.outlet?.outlet_id||outletName(a);if(!m.has(id))m.set(id,{id,name:outletName(a),type:a.outlet?.outlet_type||"Outlet",actions:0,high:0,orders:0,demand:0});let x=m.get(id);x.actions++;x.high+=a.priority==="HIGH"?1:0;x.orders+=a.recommendation?.action==="REPLENISH"?1:0;x.demand+=Number(a.forecast?.d1)||0}return [...m.values()]}
function outletCard(o){return `<article class="card"><div class="card-top"><b>${esc(o.name)}</b><span class="badge ${o.high?"high":"low"}">${o.high?o.high+" HIGH":"STABLE"}</span></div><div class="sub">${esc(o.type)} · ${esc(o.id)}</div><div class="row"><span>Actions</span><b>${n(o.actions)}</b></div><div class="row"><span>Tomorrow demand</span><b>${n(o.demand,1)}</b></div><div class="row"><span>Replenishments</span><b>${n(o.orders)}</b></div></article>`}
function renderRequirements(){let q=($("searchReq").value||"").toLowerCase(),risk=$("risk").value;let a=actions().filter(x=>(!q||`${outletName(x)} ${productName(x)}`.toLowerCase().includes(q))&&(risk==="ALL"||x.priority===risk||x.stockout_risk===risk));$("reqTable").innerHTML=a.length?a.map(x=>`<tr><td><span class="badge ${rc(x.priority)}">${esc(x.priority||"LOW")}</span></td><td><b>${esc(outletName(x))}</b></td><td>${esc(productName(x))}</td><td>${n(x.forecast?.d1,2)} ${esc(x.forecast?.unit||"")}</td><td>${n(x.inventory?.current_inventory,2)}</td><td><b>${n(x.supply?.recommended_order,2)}</b></td><td>${esc(x.stockout_risk||"LOW")}</td><td>${esc(x.recommendation?.action||"MONITOR")}</td></tr>`).join(""):`<tr><td colspan="8" style="text-align:center;color:#70798b">No matching actions.</td></tr>`}
function renderOutlets(){let q=($("searchOutlet").value||"").toLowerCase();$("outletGrid").innerHTML=outletMap().filter(o=>!q||`${o.name} ${o.id} ${o.type}`.toLowerCase().includes(q)).map(outletCard).join("")}
function renderProducts(){let q=($("searchProduct").value||"").toLowerCase(),m=new Map();for(const a of state.data.actions||[]){let id=a.product?.product_id||productName(a);if(!m.has(id))m.set(id,{id,name:productName(a),category:a.product?.category||"Product",demand:0,high:0,orders:0});let x=m.get(id);x.demand+=Number(a.forecast?.d1)||0;x.high+=a.priority==="HIGH"?1:0;x.orders+=a.recommendation?.action==="REPLENISH"?1:0}$("productGrid").innerHTML=[...m.values()].filter(p=>!q||`${p.name} ${p.id} ${p.category}`.toLowerCase().includes(q)).sort((a,b)=>b.demand-a.demand).map(p=>`<article class="product"><h3>${esc(p.name)}</h3><small>${esc(p.category)} · ${esc(p.id)}</small><div class="number">${n(p.demand,1)}</div><div class="label">projected tomorrow</div><p><span class="badge ${p.high?"high":"low"}">${n(p.high)} high risk</span> <span class="badge moderate">${n(p.orders)} orders</span></p></article>`).join("")}
function page(name){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));$(name).classList.add("active");document.querySelector(`[data-page="${name}"]`)?.classList.add("active");const t={overview:["Tomorrow's business overview","See what every outlet needs before tomorrow."],requirements:["Tomorrow's Requirements","Every outlet-product action returned by the model."],outlets:["Outlets","All outlets represented in the response."],products:["Products","Tomorrow's projected demand by product."]}[name];$("title").textContent=t[0];$("subtitle").textContent=t[1]}
function demoPayload(){const sales=[],start=new Date("2026-01-01T00:00:00Z"),series=[["O001","P001",58,.22],["O001","P002",42,.12],["O002","P001",47,.08],["O002","P002",35,.18],["O003","P001",64,.15],["O003","P002",29,.05]];for(let i=0;i<43;i++){let d=new Date(start);d.setUTCDate(start.getUTCDate()+i);for(const [o,p,b,g] of series){let w=[0,6].includes(d.getUTCDay())?1.12:1;sales.push({date:d.toISOString().slice(0,10),outlet_id:o,product_id:p,quantity_sold:Math.max(1,Math.round(b*(1+g*i/42)*w))})}}return{client_id:"dashboard_demo",as_of_date:"2026-02-12",sales,inventory:series.map((x,i)=>({outlet_id:x[0],product_id:x[1],current_inventory:i%3===0?65:120,lead_time_days:3,safety_stock:10,minimum_order_quantity:20,order_multiple:5,supplier_risk:i%4===0?"MODERATE":"LOW"})),outlets:[{outlet_id:"O001",outlet_name:"Agra Main Restaurant",outlet_type:"restaurant",country:"India",region:"Uttar Pradesh",city:"Agra"},{outlet_id:"O002",outlet_name:"Delhi Cloud Kitchen",outlet_type:"cloud_kitchen",country:"India",region:"Delhi",city:"New Delhi"},{outlet_id:"O003",outlet_name:"Noida Restaurant Bar",outlet_type:"restaurant_bar",country:"India",region:"Uttar Pradesh",city:"Noida"}],products:[{product_id:"P001",product_name:"Chicken",category:"protein",unit:"kg"},{product_id:"P002",product_name:"Rice",category:"grain",unit:"kg"}],top_n:50,include_normal:true}}
async function loadDemo(){try{state.data=await api(demoPayload());render();toast("Demo data loaded from the live ML API.")}catch(e){connection(false,"Unavailable");toast(e.message)}}
async function testApi(){try{let r=await fetch(state.api.replace(/\/$/,"")+"/api/v1/client/health");if(!r.ok)throw Error("HTTP "+r.status);connection(true,"Connected")}catch(e){connection(false,"Unavailable")}}
$("demo").onclick=loadDemo;$("emptyDemo").onclick=loadDemo;$("upload").onclick=()=>$("file").click();$("emptyUpload").onclick=()=>$("file").click();
$("file").onchange=async e=>{let f=e.target.files?.[0];if(!f)return;try{state.data=await api(JSON.parse(await f.text()));render();toast("Client data processed successfully.")}catch(x){toast("Upload failed: "+x.message)}e.target.value=""};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>page(b.dataset.go));["searchReq","risk","searchOutlet","searchProduct"].forEach(id=>$(id).addEventListener("input",render));
$("settings").onclick=()=>{$("apiUrl").value=state.api;$("modal").classList.remove("hidden")};$("close").onclick=()=>$("modal").classList.add("hidden");$("save").onclick=()=>{let v=$("apiUrl").value.trim().replace(/\/$/,"");if(!v)return;state.api=v;localStorage.setItem("rdai_api_url",v);$("modal").classList.add("hidden");testApi();toast("API URL saved.")};$("test").onclick=testApi;
render();testApi();
